name: Build master

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [3.1.100]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        # Fix for https://github.com/actions/setup-dotnet/issues/29#issuecomment-548740241
        uses: actions/setup-dotnet@bb95ce727fd49ec1a65933419cc7c91747785302
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore local tools
        run: dotnet tool restore
      - name: Build
        run: dotnet fake run build.fsx